### PR TITLE
Multiple different fixes relation to dungeons.

### PR DESCRIPTION
**Pull request by Mannybrado**
## Description

Changes things relating to dungeon loot and the cheeseablitlity/difficulty of some dungeons.
**Sunnydale:**
 Enclave Bunker:
Extends the dense rock a bit closer around the entrance to prevent any skipping. 
Replaces all of the protectrons with gutsies. This is lore accurate.
Adds four sentry boys and doubles the amount of guties on the bottom floor. It will now take some serious thinking in order to figure out how to get into the loot room without the sentry bots dying and blowing up all the loot.
 BoS base: 
Places dense rock around the whole bunker so they have to leave to mine resources.
 Legion base: 
Removes the dense rock from the left side of the base and reorganizes the spawns so people spawn generally closer to each other. 
 NCR base: 
Reorganizes spawns like the Legion base. Rangers untouched.
 Tunnel bunker: 
Puts dense rock around the whole thing.
 Deathclaw cave:
Puts dense rock around the whole thing.
 Commie vault:
In engineering and security, all of the ghouls have been replaced with protectrons.
In engineering, the final enemy is a robobrain.
In engineering in the cave, there are now 3 deathclaws and a mother deathclaw. There is now a t3 armor spawn and another t4 ammo spawn, on top of the t4 gun spawn.
In security, in the armory, there is now a sentry bot. A t4 gun and ammo spawn has been put in with it as well.
Botany now has a seed extractor and biogenerator, as well as a sink.
There is now a chem book in medical.

i think thats all for sunny
**Pahrump:**
BoS base:
Puts dense rock around the whole bunker so that they have to leave to mine resources.

yeah thats all
## Motivation and Context

Fuck metarushers. And BoS.
## How Has This Been Tested?

locally
## Screenshots (if appropriate):
Enclave Bunker: 
image
image
Tunnel Bunker and Deathclaw Cave:
image
BoS base on both maps:
sunny
image
pahrmp
image
Legion base:
image
NCR base:
image
Commie Vault:
image
image

## Changelog (necessary)
:cl:
del: erp room
fix: things
/:cl:

### CODE REVIEW

**Comment by ErwinSnowden** [comment]
Too radical of changes. Also, you literally just spammed sentrybots on top of eachother like an autist in the enclave bunker because you're angry with people actually getting the loot at the end, for the problem players (myself), this wont do ANYTHING because I know how to lure sentrybots into the sentry array and get them killed there, what this does is make it substantially harder (near impossible actually) for anyone who isn't me from doing the bunker. 

I really hope this doesn't get merged because it literally makes flanks on the BoS impossible by removing digging into their bunker on Pahrump. (As well as making it infinitely easier to flank the other factions on both maps.)

Also, I just want to add how this is such a grudge PR that you failed to even account for the fact that the turrets will shoot the gutsies that you placed in the middle of the turret room roundstart. You haven't tested this at all or made any attempt to even make sure that it's clearable in the current state. In short uh.... get good? Also it doesn't make sense how the enclave would have more gutsies in an installation than actual personnel. (It's already really crowded in there.)

**Comment by Mannybrado** [comment]
Okay powergamer. Let me fix it.

**Comment by Mannybrado** [comment]
also, uh, "flanks on the BoS"? really? do you not actually understand how dogshit meta it is to spend half an hour mining 70 tiles in a random direction to get to the BoS bunker? really?

**Comment by Mannybrado** [comment]
I moved the sentry bots in the bottom level to where the turrets are, and deleted the turrets. The only way to beat this is through brute force with, probably, multiple people. Or a lot of patience and no fuck ups. Its meant to be hard. This removes some of the cheese.

**Comment by Mannybrado** [comment]
and deleted the gutsy next to the turrets. i didnt know. i dont really care, but whatever.

**Comment by ErwinSnowden** [comment]
> I moved the sentry bots in the bottom level to where the turrets are, and deleted the turrets. The only way to beat this is through brute force with, probably, multiple people. Or a lot of patience and no fuck ups. Its meant to be hard. This removes some of the cheese.

you can just throw (heated) blackpowder bottles at them to kill them, or just kill one and have the resulting explosion take down most of the other's health. i think that a total re-map of the enclave bunker is necessary to make it more deserving of the loot, instead of having one central vault where all of the good shit is, having the loot spread out throughout multiple locations in the bunker so it overall takes longer is the better choice.

**Comment by ewm1917** [comment]
Bad

**Comment by Mannybrado** [comment]
...eh. there's only so much you can do with simple mobs.

**Comment by Zach720** [comment]
This is cum.

**Pull request merged**
