### PR TITLE
Throwing Spear Balance!

### PR DESCRIPTION
**Pull request by SquishyOranges**
## Description
Throwing spear gets some sick balance changes!

## Motivation and Context
It made no sense why a throwing spear wouldn't stay in or embed most of the time.

## Changelog (necessary)
:cl:
balance: rebalanced throwing spears!
/:cl:

### CODE REVIEW

**Comment by Sparrowbird611** [comment]
Tbh, I'd like to ask if you could remove the "slow while in hand" thing. I don't think they should slow you like guns do, especially since they have a delay before they can be thrown.

**Comment by SquishyOranges** [comment]
> Tbh, I'd like to ask if you could remove the "slow while in hand" thing. I don't think they should slow you like guns do, especially since they have a delay before they can be thrown.

I did remove the slowdown!

**Comment by Sparrowbird611** [comment]
You should probably remove that item_flag then.

**Comment by SquishyOranges** [comment]
> You should probably remove that item_flag then.

Nah, no need. It works fine

**Comment by Sparrowbird611** [comment]
Odd. I still think it's weird to leave it in, especially if it doesn't seem to do anything, but I guess that's up to you.

**Pull request merged**
